# -*- coding: utf-8 -*-
"""Copia di MLDL - Lab02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DnrXOV0c5aUzs8xCnajS90SHokJ04PnN

# Lab 02: Training a Custom Model

**Objective of this lab**: training a small custom model on the Tiny-ImageNet dataset.

## Dataset preparation
"""

!wget http://cs231n.stanford.edu/tiny-imagenet-200.zip
!unzip tiny-imagenet-200.zip -d tiny-imagenet

"""We need to adjust the format of the val split of the dataset to be used with ImageFolder."""

import os
import shutil

with open('tiny-imagenet/tiny-imagenet-200/val/val_annotations.txt') as f:
    for line in f:
        fn, cls, *_ = line.split('\t')
        os.makedirs(f'tiny-imagenet/tiny-imagenet-200/val/{cls}', exist_ok=True)

        shutil.copyfile(f'tiny-imagenet/tiny-imagenet-200/val/images/{fn}', f'tiny-imagenet/tiny-imagenet-200/val/{cls}/{fn}')

shutil.rmtree('tiny-imagenet/tiny-imagenet-200/val/images')

from torchvision.datasets import ImageFolder
import torchvision.transforms as T

transform = T.Compose([
    T.Resize((224, 224)),  # Resize to fit the input dimensions of the network
    T.ToTensor(),
    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

# root/{classX}/x001.jpg

tiny_imagenet_dataset_train = ImageFolder(root='tiny-imagenet/tiny-imagenet-200/train', transform=transform)
tiny_imagenet_dataset_val = ImageFolder(root='tiny-imagenet/tiny-imagenet-200/val', transform=transform)

print(f"Length of train dataset: {len(tiny_imagenet_dataset_train)}")
print(f"Length of val dataset: {len(tiny_imagenet_dataset_val)}")

# The following code also checks the number of samples per class, 200 classi con 50 entries ciascuno
# from collections import Counter

# class_counts = Counter([target for _, target in tiny_imagenet_dataset_val])
# for class_label, count in class_counts.items():
#     print(f"Class {class_label}: {count} entries")

import torch
train_loader = torch.utils.data.DataLoader(tiny_imagenet_dataset_train, batch_size=32, shuffle=True, num_workers=2)
val_loader = torch.utils.data.DataLoader(tiny_imagenet_dataset_val, batch_size=32, shuffle=False)

"""## Custom model definition"""

import torch
from torch import nn

# Define the custom neural network
class CustomNet(nn.Module):
    def __init__(self):
        super(CustomNet, self).__init__()
        # Define layers of the neural network

        # aggiungo activation function: DEFINISCO UNA SOLA VOLTA
        self.leaky_relu = nn.LeakyReLU() #slope: 0.01

        self.conv1 = nn.Conv2d(3, 64, kernel_size=3, padding=1, stride=1)
        #3 canali input, #64: È il numero di canali di output

        self.batchnorm1 = nn.BatchNorm2d(64)

        #DEFINISCO UNA SOLA VOLTA E CHIAMO DOPO OGNI conv
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2) # 224x224 -> 112x112

        self.conv2 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        #64 canali input, #128: È il numero di canali di output

        self.batchnorm2 = nn.BatchNorm2d(128)


        # Add more layers...
        self.conv3 = nn.Conv2d(128,256, kernel_size=3, padding=1)
        self.batchnorm3 = nn.BatchNorm2d(256)

        #arrivato qui sara di dimensione 256x28x28
        self.conv4 = nn.Conv2d(256,512,kernel_size=4, padding=1,stride=2) # 28+2-4 /2 +1 512x14x14
        self.batchnorm4 = nn.BatchNorm2d(512)

        self.conv5 = nn.Conv2d(512,512,kernel_size=4, padding=1,stride=2) # 14 -4+2/2 +1 512x7x7
        self.batchnorm5 = nn.BatchNorm2d(512)

        self.conv6 = nn.Conv2d(512,512,kernel_size=3, padding=1,stride=2) # 7 -4+3/2 +1 512x3x3
        self.batchnorm6 = nn.BatchNorm2d(512)

        self.conv7 = nn.Conv2d(512,256,kernel_size=3,stride=1) # 3 - 2/ 1 + 1 256x1x1
        self.batchnorm7 = nn.BatchNorm2d(256)

        # Usiamo l'Adaptive Pooling Globale
        self.avgpool = nn.AdaptiveAvgPool2d((1, 1)) # 28x28 -> 1x1

        #flattern per avere 256 al posto di Bx256x1x1
        self.flatten = nn.Flatten(start_dim=1) # parte quindi da 256 in poi e appiattisce tutto senza cambiare quella del batch

        self.fc1 = nn.Linear(256, 200) # 200 is the number of classes in TinyImageNet

    def forward(self, x): #x input
        # Define forward pass
        # da provare conv -> batch norm ->leaky -> pool  per piu passaggi aumentando Cout (512) aggiustando dimensioni di avg pool alla fine

        # B x 3 x 224 x 224
        x = self.conv1(x) # B x 64 x 224 x 224
        x = self.batchnorm1(x);
        x = self.leaky_relu(x)
        x = self.pool(x) # Bx64x112x112

        x = self.conv2(x)  # Bx 128 x112x112
        x = self.batchnorm2(x);
        x = self.leaky_relu(x)
        x = self.pool(x) # Bx128x56x56

        x = self.conv3(x)  # Bx 256 x56x56
        x = self.batchnorm3(x);
        x = self.leaky_relu(x)
        x = self.pool(x) # Bx256x28x28

        x = self.conv4(x)  # Bx 512 x28x28
        x = self.batchnorm4(x);
        x = self.leaky_relu(x)
        x = self.pool(x) # Bx512x14x14

        x = self.conv5(x)  # Bx 512 x14x14
        x = self.batchnorm5(x);
        x = self.leaky_relu(x)
        x = self.pool(x) # Bx512x7x7

        x = self.conv6(x)  # Bx 512 x7x7
        x = self.batchnorm6(x);
        x = self.leaky_relu(x)
        x = self.pool(x) # Bx512x3x3

        x = self.conv7(x)  # Bx 512 x3x3
        x = self.batchnorm7(x);
        x = self.leaky_relu(x)
        # NON HO BISOGNO DI POOLING !!! x = self.pool(x) # Bx256x1x1

        x = self.avgpool(x) # Bx256x1x1

        x = self.flatten(x) # Bx256
        x = self.fc1(x)


        return x

def train(epoch, model, train_loader, criterion, optimizer):
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0
    # loss_function = nn.CrossEntropyLoss() #cross entropy -[y *log(p) + (1-y) * log(1-p)]
    # optimizer = torch.optim.SGD(model.parameters(),lr=0.001, momentum=0.9)

    for batch_idx, (inputs, targets) in enumerate(train_loader):
        inputs, targets = inputs.cuda(), targets.cuda()

        # todo...
        # pred, loss, azzero_grad, backward, step
        pred = model(inputs)
        loss = criterion(pred,targets) #tra pred e real

        optimizer.zero_grad()
        loss.backward() #calcola gra
        optimizer.step() #fa il passo

        running_loss += loss.item()
        _, predicted = pred.max(1)
        total += targets.size(0)
        correct += predicted.eq(targets).sum().item()

    train_loss = running_loss / len(train_loader)
    train_accuracy = 100. * correct / total
    print(f'Train Epoch: {epoch} Loss: {train_loss:.6f} Acc: {train_accuracy:.2f}%')

# Validation loop
def validate(model, val_loader, criterion):
    model.eval()
    val_loss = 0

    correct, total = 0, 0

    with torch.no_grad(): # importante perche non voglio barare e quindi non aggiorno weigth in test
        for batch_idx, (inputs, targets) in enumerate(val_loader):
            inputs, targets = inputs.cuda(), targets.cuda()

            # todo...
            pred = model(inputs)
            loss = criterion(pred,targets) #calcolo la loss

            val_loss += loss.item()
            _, predicted = pred.max(1)
            total += targets.size(0)
            correct += predicted.eq(targets).sum().item()

    val_loss = val_loss / len(val_loader)
    val_accuracy = 100. * correct / total

    print(f'Validation Loss: {val_loss:.6f} Acc: {val_accuracy:.2f}%')
    return val_accuracy

"""## Putting everything together"""

model = CustomNet().cuda()
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.001, momentum=0.9)

best_acc = 0

# Run the training process for {num_epochs} epochs
num_epochs = 20
for epoch in range(1, num_epochs + 1):
    train(epoch, model, train_loader, criterion, optimizer)

    # At the end of each training iteration, perform a validation step
    val_accuracy = validate(model, val_loader, criterion)

    # Best validation accuracy
    best_acc = max(best_acc, val_accuracy)


print(f'Best validation accuracy: {best_acc:.2f}%')

